### PR TITLE
[#261] Server now handles "+" special character

### PR DESCRIPTION
**Pull request by korydraughn**
The `@RequestParam` annotation automatically decodes values.

### CODE REVIEW

**Comment by trel** [comment]
it handles it by just ... not decoding it?

**Comment by korydraughn** [comment]
the annotation is provided by the spring framework. it automatically decodes the string for us. we were decoding the string again which caused the **plus (+)** sign to be removed.

**Comment by korydraughn** [comment]
this just means we don't have to worry about decoding any incoming request data.

**Comment by trel** [comment]
the best of answers - please # it.

**Comment by korydraughn** [comment]
added #

**Pull request merged**
