### PR TITLE
[332] Set createParentCollections to true 

### PR DESCRIPTION
**Pull request by JustinKyleJames**
Updated the code to call the new method with sets createParentCollections to true.

### CODE REVIEW

**Comment by trel** [comment]
if second parameter changes name, update this commit message.

**Comment by JustinKyleJames** [comment]
> if second parameter changes name, update this commit message.

I changed the commit message.  Had to force push to get the change.

**Comment by trel** [comment]
needs to be plural - please re-force push.

createParentCollections

**Comment by JustinKyleJames** [comment]
I updated the commit message to refer to createParentCollections and forced push it.

**Comment by JustinKyleJames** [comment]
Pound is done.

**Comment by trel** [comment]
Merging.

**Pull request merged**
