### PR TITLE
Add new configuration to build image by using multistage builds

### PR DESCRIPTION
**Pull request by he0s**
This approach should simplify the whole build pipeline, because
it runs all the building steps consistently.

### CODE REVIEW

**Comment by michael-conway** [comment]
Nice! I'll try and check ASAP. Thanks

**Comment by he0s** [comment]
@michael-conway, please have a look at #145 as well, since I can't use the application if I build it in either way.

**Comment by michael-conway** [comment]
Yep, check the comment on 145, I think it's just a missing config property.
it's angry when trying to interpolate metalnx.properties and finding a
missing val

**Comment by he0s** [comment]
@michael-conway by the way, I see your initial Dockerfile copies the tomcat's configuration file in the separate directory: `COPY packaging/docker/server.xml /conf/server.xml`. Is it okay or this step should be fixed as well?

**Comment by michael-conway** [comment]
It should be incorporated to increase max upload, this was another issue.
Still needed testing tho!

**Comment by he0s** [comment]
Okay, I'll incorporate it into my original file and test.

**Pull request merged**
