### PR TITLE
#76 refactor into single monolithic war file

### PR DESCRIPTION
**Pull request by michael-conway**
This is a significant (tho in the end produces an equivalent .war file) that collapses files scattered over multiple subprojects into one simple .war file structure.

This is a first step towards moving into a 'war' overlay model and is **targeted at development and version 2.1.0**. The difference is in the source code layout. In the end the generated war artifact remains the same, as the current build combines the code from the various subprojects as a set of related .jar files. This change is meant to simplify development and code editing.

### CODE REVIEW

**Comment by michael-conway** [comment]
NB adding a patch to the build for template handling

**Comment by trel** [comment]
if the build and packaging are still in working order, let's merge this.

**Comment by michael-conway** [comment]
It does not impact the build/package and makes life much simpler for the dev. I'll go ahead and merge into the master, this can be the core of the next release activities.

**Comment by trel** [comment]
very good.  thanks!

**Pull request merged**
